
downloadSRR: True

samples:
  - SRR24597727

## Gtf input
gtf_file: "annotation/XENLA_10.1_Xenbase_2025-09-15.gtf"

## Reference genome
genome: "genome/XENLA_10.1_genome.fa"

## Check if initial files are compressed (.gz)
## Flag this True if your downloadSRR is False and your input files are in .gz format
iscompressed: False

## Check if your input is a fastq or a BAM
from_fastq: True

## trim adapter
runtrimming: True

## Check quality of fastq
## FastQC and MultiQC check

gen_fastqc: True
gen_multiqc: True

## Parameters for trimmomatic
## Adapter file
#trimmomatic_adapter: "TruSeq3-PE.fa"

## Trimming options
trimmotatic_minlen: 30

## Genome annotation and indexing
## Genome annotation includes generating exon and splice sites
genome_anno: True

genome_build: True
genome_index_dir: "genome_build"

## Alignment

use_hisat: True
use_star: False

## Count table generation

use_featurecount: True
use_htseq: False

## Calculate TPM

calc_tpm: False


## deseq2 

use_deseq: False